# Copyright 2023 SECO Mind Srl
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  reuse:
    uses: ./.github/workflows/reuse-lint.yaml
  nix:
    needs: [ reuse ]
    uses: ./.github/workflows/nix.yaml
  elixir:
    needs: [ reuse ]
    uses: ./.github/workflows/elixir.yaml
